[IMP] Co-SLAM: add modifications to use the algorithm without cuda
Changelog:
- Add submodule hash-grid-encoding that has encoding implementations
  withoud tynicudann.
- Add submodule pytorch3d because it can not be installed by pip or
  conda.
- Replace encodings with the encodings in the new submodule.
- Use float method to convert to float32 the inputs to the networks in
  order to match the type of the weight matrix [1]. This solves the
  error: RuntimeError: expected m1 and m2 to have the same dtype, but
  got: double != float

[1] https://discuss.pytorch.org/t/runtimeerror-mat1-and-mat2-must-have-the-same-dtype/166759/2